


    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        port: 22
        timeout: 180s
        command_timeout: 10m
        request_pty: true
        debug: true
        script: |
          pwd
          whoami
          cd /home/ec2-user/app/SpringCICD
          ls
          ./deploy.sh



